### ISSUE TITLE
下载Demo编译后无法运行

### ISSUE THREAD

**Issue by linrongxin** [easefun/polyv-android-sdk-demo#7]
你好，我下载了master和release的Demo,放到eclipse里，编译成功后，运行失败异常退出，异常信息：
java.lang.NoClassDefFoundError: com.easefun.polyvsdk.PolyvSDKClient
    at com.easefun.polyvsdk.demo.MyApplication.initPolyvCilent(MyApplication.java:77)
    at com.easefun.polyvsdk.demo.MyApplication.onCreate(MyApplication.java:64)
...
我使用的是 target=android-18

**Comment by linrongxin** [comment]
jar包存在，也成功导入

**Comment by tanqu2013** [comment]
您好，请问您的问题解决了吗？
